# Generated by Django 6.0.3 on 2026-04-13 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.CharField(max_length=50, unique=True)),
                ('key', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('patch', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('plaintext', models.CharField(blank=True, max_length=500)),
                ('gold_total', models.IntegerField(default=0)),
                ('gold_base', models.IntegerField(default=0)),
                ('purchasable', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('patch', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RunePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=200)),
                ('patch', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SummonerSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.CharField(max_length=50, unique=True)),
                ('key', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cooldown', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('patch', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('row', models.IntegerField(default=0)),
                ('short_description', models.TextField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=200)),
                ('patch', models.CharField(blank=True, max_length=20)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runes', to='lol.runepath')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_type', models.CharField(choices=[('passive', 'Passive'), ('Q', 'Q'), ('W', 'W'), ('E', 'E'), ('R', 'R')], max_length=10)),
                ('riot_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cooldown', models.JSONField(blank=True, default=list)),
                ('cost', models.JSONField(blank=True, default=list)),
                ('max_rank', models.IntegerField(default=5)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='lol.champion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('champion', 'ability_type'), name='unique_champion_ability')],
            },
        ),
    ]
