# Generated by Django 6.0.3 on 2026-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lol", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="champion",
            name="icon",
            field=models.ImageField(blank=True, upload_to="champions/"),
        ),
    ]
