# Generated by Django 6.0.3 on 2026-04-13 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='leagues/')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('leaguepedia_page', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('real_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('birthdate', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('leaguepedia_page', models.CharField(blank=True, max_length=200, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.league')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=200, unique=True)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('winner', models.IntegerField(blank=True, null=True)),
                ('best_of', models.IntegerField(default=3)),
                ('tab', models.CharField(blank=True, max_length=100)),
                ('datetime_utc', models.DateTimeField(blank=True, null=True)),
                ('patch', models.CharField(blank=True, max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.event')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['datetime_utc'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=200, unique=True)),
                ('game_number', models.IntegerField(default=1)),
                ('datetime_utc', models.DateTimeField(blank=True, null=True)),
                ('patch', models.CharField(blank=True, max_length=20)),
                ('gamelength', models.CharField(blank=True, max_length=10)),
                ('winner', models.IntegerField(blank=True, null=True)),
                ('vod', models.URLField(blank=True)),
                ('team1', models.CharField(max_length=100)),
                ('team1_kills', models.IntegerField(default=0)),
                ('team1_gold', models.IntegerField(default=0)),
                ('team1_towers', models.IntegerField(default=0)),
                ('team1_dragons', models.IntegerField(default=0)),
                ('team1_barons', models.IntegerField(default=0)),
                ('team1_rift_heralds', models.IntegerField(default=0)),
                ('team2', models.CharField(max_length=100)),
                ('team2_kills', models.IntegerField(default=0)),
                ('team2_gold', models.IntegerField(default=0)),
                ('team2_towers', models.IntegerField(default=0)),
                ('team2_dragons', models.IntegerField(default=0)),
                ('team2_barons', models.IntegerField(default=0)),
                ('team2_rift_heralds', models.IntegerField(default=0)),
                ('team1_bans', models.ManyToManyField(blank=True, related_name='team1_bans', to='lol.champion')),
                ('team1_picks', models.ManyToManyField(blank=True, related_name='team1_picks', to='lol.champion')),
                ('team2_bans', models.ManyToManyField(blank=True, related_name='team2_bans', to='lol.champion')),
                ('team2_picks', models.ManyToManyField(blank=True, related_name='team2_picks', to='lol.champion')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core.match')),
            ],
            options={
                'ordering': ['game_number'],
            },
        ),
        migrations.CreateModel(
            name='TeamRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='core.event')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RosterPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Top', 'Top'), ('Jungle', 'Jungle'), ('Mid', 'Mid'), ('Bot', 'Bot'), ('Support', 'Support'), ('Coach', 'Coach'), ('Sub', 'Sub')], max_length=10)),
                ('is_starter', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='core.player')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.teamroster')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('team', models.CharField(max_length=100)),
                ('side', models.IntegerField(default=1)),
                ('role', models.CharField(max_length=20)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('cs', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('damage_to_champions', models.IntegerField(default=0)),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lol.champion')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='core.game')),
                ('items', models.ManyToManyField(blank=True, related_name='performances', to='lol.item')),
                ('keystone_rune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keystone_performances', to='lol.rune')),
                ('runes', models.ManyToManyField(blank=True, related_name='performances', to='lol.rune')),
                ('summoner_spell_d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spell_d_performances', to='lol.summonerspell')),
                ('summoner_spell_f', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spell_f_performances', to='lol.summonerspell')),
                ('trinket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trinket_performances', to='lol.item')),
            ],
            options={
                'ordering': ['side', 'role'],
                'constraints': [models.UniqueConstraint(fields=('game', 'name', 'team'), name='unique_player_game')],
            },
        ),
    ]
