# Generated by Django 6.0.3 on 2026-04-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_fully_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
