# Generated by Django 6.0.4 on 2026-05-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_event_is_fully_synced_event_last_synced_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"verbose_name_plural": "matches"},
        ),
        migrations.AlterField(
            model_name="player",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerperformance",
            name="side",
            field=models.IntegerField(choices=[(1, "Blue"), (2, "Red")], default=1),
        ),
    ]
