# Generated by Django 6.0.4 on 2026-05-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_match_options_alter_player_birthdate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="leaguepedia_page",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
