# Generated by Django 6.0.4 on 2026-05-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_player_leaguepedia_page_alter_player_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="leaguepedia_image",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
