# Generated by Django 6.0.4 on 2026-05-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_player_leaguepedia_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="color",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
    ]
