# Generated by Django 6.0.4 on 2026-05-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_organization_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="gold_graph",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="riot_platform_game_id",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="game",
            name="riot_platform_id",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
