# Generated by Django 6.0.4 on 2026-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_game_gold_graph_game_riot_platform_game_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="prize_pool",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
