# Generated by Django 6.0.4 on 2026-06-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_event_prize_pool"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="instagram",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="league",
            name="twitter",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="league",
            name="youtube",
            field=models.URLField(blank=True, default=""),
        ),
    ]
