# Generated by Django 6.0.4 on 2026-06-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_league_social_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="twitch",
            field=models.URLField(blank=True, default=""),
        ),
    ]
