# Generated by Django 6.0.3 on 2026-06-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_league_twitch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="short_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="short_name",
            field=models.CharField(max_length=50),
        ),
    ]
