# Generated by Django 6.0.3 on 2026-06-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_league_short_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerperformance",
            name="role",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="rosterplayer",
            name="role",
            field=models.CharField(
                choices=[
                    ("Top", "Top"),
                    ("Jungle", "Jungle"),
                    ("Mid", "Mid"),
                    ("Bot", "Bot"),
                    ("Support", "Support"),
                    ("Coach", "Coach"),
                    ("Sub", "Sub"),
                ],
                max_length=50,
            ),
        ),
    ]
