# Generated by Django 6.0.3 on 2026-06-11 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_playerperformance_role_alter_rosterplayer_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_enriched",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playerperformance",
            name="vision_score",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PerformanceAdvanced",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("golddiffat10", models.FloatField(blank=True, null=True)),
                ("golddiffat15", models.FloatField(blank=True, null=True)),
                ("csdiffat15", models.FloatField(blank=True, null=True)),
                ("xpdiffat15", models.FloatField(blank=True, null=True)),
                ("damageshare", models.FloatField(blank=True, null=True)),
                ("earnedgoldshare", models.FloatField(blank=True, null=True)),
                ("damagetakenperminute", models.FloatField(blank=True, null=True)),
                ("damagemitigatedperminute", models.FloatField(blank=True, null=True)),
                ("vspm", models.FloatField(blank=True, null=True)),
                ("wpm", models.FloatField(blank=True, null=True)),
                ("wardskilled", models.IntegerField(blank=True, null=True)),
                ("controlwardsbought", models.IntegerField(blank=True, null=True)),
                (
                    "performance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advanced",
                        to="core.playerperformance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pr", models.FloatField(default=0)),
                ("points", models.FloatField(default=0)),
                (
                    "tier",
                    models.CharField(
                        choices=[("enriched", "Enriched"), ("basic", "Basic")],
                        default="basic",
                        max_length=10,
                    ),
                ),
                ("is_mvp", models.BooleanField(default=False)),
                ("contribution_share", models.FloatField(default=0)),
                ("metric_breakdown", models.JSONField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "performance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="core.playerperformance",
                    ),
                ),
            ],
        ),
    ]
