# Generated by Django 6.0.3 on 2026-06-18 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_game_is_enriched_playerperformance_vision_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("league", "League"),
                            ("playoff", "Playoff"),
                            ("swiss", "Swiss"),
                            ("group", "Group"),
                            ("play_in", "Play-In"),
                        ],
                        default="league",
                        max_length=20,
                    ),
                ),
                ("is_lower_bracket", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "leaguepedia_page",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="core.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="match",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches",
                to="core.eventstage",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventstage",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="unique_stage_per_event"
            ),
        ),
    ]
