# Generated by Django 6.0.3 on 2026-06-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_eventstage_match_stage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventstage",
            old_name="is_lower_bracket",
            new_name="has_lower_bracket",
        ),
        migrations.AddField(
            model_name="match",
            name="is_lower_bracket",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="next_match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_matches",
                to="core.match",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="previous_match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_matches",
                to="core.match",
            ),
        ),
    ]
