# Generated by Django 6.0.3 on 2026-06-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_rename_is_lower_bracket_eventstage_has_lower_bracket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="bracket_order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                condition=models.Q(("bracket_order__isnull", False)),
                fields=("event", "tab", "bracket_order"),
                name="unique_bracket_order_per_round",
            ),
        ),
    ]
