# Generated by Django 6.0.3 on 2026-06-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_bracket_order"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="match",
            name="unique_bracket_order_per_round",
        ),
        migrations.AddField(
            model_name="match",
            name="bracket_col",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("bracket_col__isnull", False), ("bracket_order__isnull", False)
                ),
                fields=("event", "bracket_col", "bracket_order"),
                name="unique_bracket_order_per_col",
            ),
        ),
    ]
