# Generated by Django 6.0.3 on 2026-07-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_match_is_final"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="match",
            name="unique_bracket_order_per_col",
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("bracket_col__isnull", False), ("bracket_order__isnull", False)
                ),
                fields=(
                    "event",
                    "stage",
                    "is_lower_bracket",
                    "bracket_col",
                    "bracket_order",
                ),
                name="unique_bracket_order_per_col",
            ),
        ),
    ]
