# Generated by Django 6.0.3 on 2026-10-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_match_unique_bracket_order_per_col_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bracket_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
