# Generated by Django 6.0.3 on 2026-10-05 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_match_bracket_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='loser_next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser_previous_matches', to='core.match'),
        ),
    ]
