# Generated by Django 6.0.3 on 2026-10-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_loser_bracket_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bracket_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
