# Generated by Django 6.0.3 on 2026-10-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_persistent_bracket_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='loser_outcome',
            field=models.CharField(choices=[('auto', 'Automatic'), ('eliminated', 'Eliminated'), ('lower', 'Lower bracket'), ('none', 'Hide label')], default='auto', max_length=12),
        ),
    ]
