# Generated by Django 6.0.3 on 2026-10-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_loser_outcome_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_origin',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_origin',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
