# Generated by Django 6.0.3 on 2026-10-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_match_entry_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bracket_entries',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
